const db = require('../config/db');

const getAllHotelCards = async () => {
  try {
    console.log("DAO: getAllHotelCards called - returning mock data");
    
    // Mock data for all hotel cards - same as search results but all hotels
    const mockHotels = [
      {
        property_id: 1,
        property_name: 'Taj Lands End',
        star_category: 5,
        city_name: 'Mumbai',
        state_name: 'Maharashtra',
        image_name: 'taj_lands_end.jpg',
        room_type: 'Deluxe Room',
        max_adult: 2,
        total_rooms: 356,
        old_price: 25000,
        price: 20000,
        currency: 'INR',
        rate_name: 'Best Available Rate',
        booking_type: 'Standard',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar,Conference Hall',
        inclusion_names: 'Breakfast,Airport Transfer,Welcome Drink',
        availability: 'Available',
        rating: '9.1 Exceptional (320)'
      },
      {
        property_id: 2,
        property_name: 'The Taj Mahal Palace Mumbai',
        star_category: 5,
        city_name: 'Mumbai',
        state_name: 'Maharashtra',
        image_name: 'taj_mahal_palace.jpg',
        room_type: 'Palace Room',
        max_adult: 2,
        total_rooms: 565,
        old_price: 30000,
        price: 25000,
        currency: 'INR',
        rate_name: 'Heritage Package',
        booking_type: 'Premium',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar,Conference Hall,Washer and dryer',
        inclusion_names: 'Breakfast,Dinner,Airport Transfer,Welcome Drink,City Tour',
        availability: 'Available',
        rating: '9.3 Exceptional (450)'
      },
      {
        property_id: 3,
        property_name: 'Oberoi Mumbai',
        star_category: 5,
        city_name: 'Mumbai',
        state_name: 'Maharashtra',
        image_name: 'oberoi_mumbai.jpg',
        room_type: 'Premier Room',
        max_adult: 2,
        total_rooms: 287,
        old_price: 22000,
        price: 18000,
        currency: 'INR',
        rate_name: 'Luxury Stay',
        booking_type: 'Standard',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar',
        inclusion_names: 'Breakfast,Airport Transfer',
        availability: 'Available',
        rating: '9.0 Exceptional (280)'
      },
      {
        property_id: 4,
        property_name: 'Hotel Delhi Palace',
        star_category: 4,
        city_name: 'Delhi',
        state_name: 'Delhi',
        image_name: 'delhi_palace.jpg',
        room_type: 'Executive Room',
        max_adult: 2,
        total_rooms: 150,
        old_price: 15000,
        price: 12000,
        currency: 'INR',
        rate_name: 'Business Rate',
        booking_type: 'Standard',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Wifi,Conference Hall',
        inclusion_names: 'Breakfast',
        availability: 'Available',
        rating: '8.5 Very Good (210)'
      },
      {
        property_id: 5,
        property_name: 'The Leela Ambience Delhi',
        star_category: 5,
        city_name: 'Delhi',
        state_name: 'Delhi',
        image_name: 'leela_delhi.jpg',
        room_type: 'Grand Room',
        max_adult: 2,
        total_rooms: 450,
        old_price: 28000,
        price: 22000,
        currency: 'INR',
        rate_name: 'Grand Package',
        booking_type: 'Premium',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar,Conference Hall',
        inclusion_names: 'Breakfast,Dinner,Airport Transfer,Welcome Drink',
        availability: 'Available',
        rating: '9.2 Exceptional (380)'
      },
      {
        property_id: 6,
        property_name: 'Taj Exotica Resort',
        star_category: 5,
        city_name: 'Goa',
        state_name: 'Goa',
        image_name: 'taj_exotica_goa.jpg',
        room_type: 'Beach Villa',
        max_adult: 2,
        total_rooms: 140,
        old_price: 35000,
        price: 28000,
        currency: 'INR',
        rate_name: 'Beach Resort Package',
        booking_type: 'Premium',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Swimming Pool,Wifi,Spa,Bar',
        inclusion_names: 'Breakfast,Dinner,Water Sports,Airport Transfer',
        availability: 'Available',
        rating: '9.4 Exceptional (500)'
      },
      {
        property_id: 7,
        property_name: 'Grand Hyatt Goa',
        star_category: 5,
        city_name: 'Goa',
        state_name: 'Goa',
        image_name: 'grand_hyatt_goa.jpg',
        room_type: 'Ocean View Room',
        max_adult: 2,
        total_rooms: 314,
        old_price: 32000,
        price: 25000,
        currency: 'INR',
        rate_name: 'Ocean Package',
        booking_type: 'Standard',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Swimming Pool,Wifi,Spa,Bar,Conference Hall',
        inclusion_names: 'Breakfast,Welcome Drink,Airport Transfer',
        availability: 'Available',
        rating: '9.1 Exceptional (390)'
      },
      {
        property_id: 8,
        property_name: 'ITC Windsor Bengaluru',
        star_category: 5,
        city_name: 'Bengaluru',
        state_name: 'Karnataka',
        image_name: 'itc_windsor.jpg',
        room_type: 'Luxury Room',
        max_adult: 2,
        total_rooms: 237,
        old_price: 18000,
        price: 15000,
        currency: 'INR',
        rate_name: 'Corporate Rate',
        booking_type: 'Standard',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Conference Hall',
        inclusion_names: 'Breakfast,Airport Transfer',
        availability: 'Available',
        rating: '8.9 Excellent (250)'
      },
      {
        property_id: 9,
        property_name: 'The Leela Palace Chennai',
        star_category: 5,
        city_name: 'Chennai',
        state_name: 'Tamil Nadu',
        image_name: 'leela_chennai.jpg',
        room_type: 'Palace Room',
        max_adult: 2,
        total_rooms: 326,
        old_price: 20000,
        price: 16000,
        currency: 'INR',
        rate_name: 'Palace Package',
        booking_type: 'Premium',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar',
        inclusion_names: 'Breakfast,Dinner,Airport Transfer,Welcome Drink',
        availability: 'Available',
        rating: '9.0 Exceptional (310)'
      },
      {
        property_id: 10,
        property_name: 'Fairmont Jaipur',
        star_category: 5,
        city_name: 'Jaipur',
        state_name: 'Rajasthan',
        image_name: 'fairmont_jaipur.jpg',
        room_type: 'Royal Room',
        max_adult: 2,
        total_rooms: 245,
        old_price: 24000,
        price: 19000,
        currency: 'INR',
        rate_name: 'Royal Package',
        booking_type: 'Premium',
        extra_beds: 1,
        max_occupancy: 3,
        amenities: 'Gym,Swimming Pool,Wifi,Spa,Bar,Conference Hall',
        inclusion_names: 'Breakfast,Dinner,Cultural Show,Airport Transfer',
        availability: 'Available',
        rating: '8.8 Excellent (270)'
      }
    ];

    console.log("DAO: Returning", mockHotels.length, "mock hotel cards");
    return mockHotels;
    
  } catch (error) {
    console.error("DAO Error in getAllHotelCards:", error);
    throw error;
  }
};
module.exports = {
  getAllHotelCards
};
